# Generated by Django 3.1.7 on 2021-03-20 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Локация')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Guest')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
